import React from 'react';
import { motion } from 'framer-motion';
import { 
  CheckCircle2, 
  MapPin, 
  Clock, 
  Stethoscope, 
  Activity,
  ArrowRight
} from 'lucide-react';

const PatientTokenCard = ({ 
  patient, 
  onComplete, 
  onCallNext,
  isLoading 
}) => {
  if (!patient) return null;

  const initials = patient.patient_name
    ? patient.patient_name.split(' ').map(n => n[0]).join('').toUpperCase()
    : '??';

  const currentTime = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  // Determination of the final destination room and floor
  const finalRoom = patient.doctor_room || patient.target_room || '-';
  const finalFloor = patient.doctor_floor || '';

  const formatDoctorName = (name) => name ? (name.startsWith('Dr') ? name : `Dr. ${name}`) : 'Any Available';

  const qrPayload = `Token: ${patient.token_number}
Patient: ${patient.patient_name || 'N/A'}
Doctor: ${formatDoctorName(patient.doctor_name)}
Room: ${finalRoom}
Triage Station: ${patient.triage_station || 'Station 1'}
Generated By: ${patient.registrar_name || 'Front Desk'}`;

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, scale: 0.9 }}
      className="premium-token-card"
    >
      {/* Status Bar */}
      <div className="card-status-indicator">
        <span className="pulse-dot"></span>
        NOW SERVING
      </div>

      {/* Logo & Brand */}
      <div className="card-brand">
        <img src="/logo.png" alt="Legacy Clinics" style={{ height: '50px', objectFit: 'contain' }} />
      </div>

      <div className="card-label">Patient Token</div>

      {/* Token Number */}
      <h1 className="token-number-display">
        {patient.token_number}
      </h1>

      {/* Department Badge */}
      <div className="dept-badge">
        <Stethoscope size={14} />
        {patient.target_dept || 'General Consultation'}
      </div>

      {/* QR Code Section */}
      <div className="qr-container">
        <img 
          src={`https://api.qrserver.com/v1/create-qr-code/?size=160x160&data=${encodeURIComponent(qrPayload)}`} 
          alt="Token QR" 
          className="qr-code-img"
        />
        <div className="patient-initials-overlay">{initials}</div>
      </div>

      {/* Location / Room */}
      <div className="location-info">
        <p className="sub-label">Proceed to</p>
        <div className="room-display">
           <MapPin size={18} className="loc-icon" />
           <span>
             {patient.doctor_name ? (
               <>
                 <span style={{ color: 'var(--brand-color)', display: 'block', fontSize: '1.1rem', fontWeight: 'bold' }}>{patient.doctor_name}</span>
                 <span>Room {finalRoom} {finalFloor && `(${finalFloor})`}</span>
               </>
             ) : (
               <span>{finalRoom} {finalFloor && `(${finalFloor})`}</span>
             )}
           </span>
        </div>
        <div style={{ marginTop: '0.75rem', padding: '0.75rem', background: 'rgba(0,0,0,0.02)', borderRadius: '12px', fontSize: '0.75rem', color: 'var(--text-muted)', display: 'flex', flexDirection: 'column', gap: '4px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
             <span><strong>Generated By:</strong> {patient.registrar_name || 'Front Desk'}</span>
             <span><strong>Triage:</strong> {patient.triage_station || 'Station 1'}</span>
          </div>
        </div>
      </div>

      {/* Footer Info */}
      <div className="card-footer-meta">
        <div className="meta-info-item">
          <Clock size={14} />
          <span>{currentTime}</span>
        </div>
        <div className="meta-info-item">
          <Activity size={14} />
          <span>Priority: {patient.priority_name || 'Standard'}</span>
        </div>
      </div>

      {/* Primary Action Button */}
      <button 
        className="finish-btn-premium" 
        onClick={() => onComplete(patient.id)}
        disabled={isLoading}
      >
        <span>Finish & Next Patient</span>
        <ArrowRight size={18} />
      </button>

      {/* Animated Background Element */}
      <div className="card-bg-glow"></div>
    </motion.div>
  );
};

export default PatientTokenCard;
