import React, { useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { 
  MapPin, 
  Clock, 
  Stethoscope, 
  Activity,
  Download,
  Share2
} from 'lucide-react';
import { toPng } from 'html-to-image';
import { QRCodeCanvas } from 'qrcode.react';

const MyTokenCard = ({ patientToken }) => {
  const cardRef = useRef(null);
  const [isDownloading, setIsDownloading] = useState(false);

  if (!patientToken) return null;

  const initials = patientToken.patient_name
    ? patientToken.patient_name.split(' ').map(n => n[0]).join('').toUpperCase()
    : '??';

  const currentTime = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  // Determination of the final destination room and floor
  const finalRoom = patientToken.doctor_room || patientToken.target_room || '-';
  const finalFloor = patientToken.doctor_floor || '';

  const formatDoctorName = (name) => name ? (name.startsWith('Dr') ? name : `Dr. ${name}`) : 'Any Available';

  const qrPayload = `Token: ${patientToken.token_number}
Patient: ${patientToken.patient_name || 'N/A'}
Doctor: ${formatDoctorName(patientToken.doctor_name)}
Room: ${finalRoom}
Triage Station: ${patientToken.triage_station || 'Station 1'}
Generated By: ${patientToken.registrar_name || 'Front Desk'}`;

  const getStatusColor = (status) => {
    switch (status.toLowerCase()) {
      case 'calling': return '#ef4444'; // Red
      case 'serving': return '#22c55e'; // Green
      default: return '#1e3a8a'; // Blue
    }
  };

  const handleDownload = async () => {
    if (!cardRef.current) return;
    
    setIsDownloading(true);
    try {
      // Ensure images are loaded. Since /logo.png is local it should be fine.
      // We use a longer delay and better options for cross-browser stability.
      await new Promise(r => setTimeout(r, 300));
      
      const dataUrl = await toPng(cardRef.current, {
        cacheBust: true,
        backgroundColor: '#ffffff',
        width: 400,
        pixelRatio: 2, // Higher quality
        style: {
          margin: '0',
          padding: '0',
          borderRadius: '24px',
          transform: 'none' // Remove any framer-motion transforms
        }
      });
      
      const link = document.createElement('a');
      link.download = `Legacy-Token-${patientToken.token_number}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error('Failed to download token image', err);
      alert('Could not generate image. This can happen on some browsers. Please try taking a screenshot instead.');
    } finally {
      setIsDownloading(false);
    }
  };

  const handleShare = async () => {
      if (navigator.share) {
          try {
              await navigator.share({
                  title: 'My Legacy Clinics Token',
                  text: `My Token Number is ${patientToken.token_number} for ${patientToken.target_dept || 'General Consultation'}.`,
                  url: window.location.href
              });
          } catch (err) {
              console.error('Share failed', err);
          }
      } else {
         handleDownload();
      }
  };

  return (
    <div className="token-download-wrapper" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center', width: '100%' }}>
      <div 
        ref={cardRef} 
        style={{ 
          background: '#ffffff', 
          borderRadius: '24px',
          width: '100%',
          maxWidth: '400px'
        }}
      >
        <motion.div 
          initial={{ opacity: 0, y: 20, scale: 0.95 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          className="premium-token-card"
          style={{ margin: '0', border: 'none' }} // Remove border for clean export
        >
          {/* Status Bar */}
          <div className="card-status-indicator" style={{ color: getStatusColor(patientToken.status), background: `${getStatusColor(patientToken.status)}15` }}>
            <span className="pulse-dot" style={{ background: getStatusColor(patientToken.status) }}></span>
            {patientToken.status.toUpperCase()}
          </div>

          {/* Logo & Brand */}
          <div className="card-brand">
            <img src="/logo.png" alt="Legacy Clinics" style={{ height: '50px', objectFit: 'contain' }} />
          </div>

          <div className="card-label">Your Active Token</div>

          {/* Token Number */}
          <h1 className="token-number-display" style={{ fontSize: '5rem', marginBottom: '10px' }}>
            {patientToken.token_number}
          </h1>

          {/* Department Badge */}
          <div className="dept-badge">
            <Stethoscope size={14} />
            {patientToken.target_dept || 'General Consultation'}
          </div>

          {/* QR Code Section */}
          <div className="qr-container" style={{ background: '#f8fafc', padding: '24px', borderRadius: '20px' }}>
            <QRCodeCanvas 
                value={qrPayload}
                size={160}
                level={"L"}
                includeMargin={false}
                imageSettings={{
                    src: "/logo.png",
                    x: undefined,
                    y: undefined,
                    height: 24,
                    width: 24,
                    excavate: true,
                }}
            />
            <div className="patient-initials-overlay" style={{ fontSize: '0.8rem', width: '36px', height: '36px' }}>{initials}</div>
          </div>

          {/* Location / Room */}
          <div className="location-info">
            <p className="sub-label">Proceed to</p>
            <div className="room-display">
               <MapPin size={18} className="loc-icon" />
               <span>
                 {patientToken.doctor_name ? (
                   <>
                     <span style={{ color: '#1e3a8a', display: 'block', fontSize: '1.1rem', fontWeight: 'bold' }}>{patientToken.doctor_name}</span>
                     <span style={{ fontSize: '1rem', color: '#64748b' }}>Room {finalRoom} {finalFloor && `(${finalFloor})`}</span>
                   </>
                 ) : (
                   <span style={{ fontSize: '1.1rem' }}>{finalRoom} {finalFloor && `(${finalFloor})`}</span>
                 )}
               </span>
            </div>
            <div style={{ marginTop: '0.75rem', padding: '0.75rem', background: '#f8fafc', borderRadius: '12px', fontSize: '0.75rem', color: '#64748b', display: 'flex', flexDirection: 'column', gap: '4px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                 <span><strong>Generated By:</strong> {patientToken.registrar_name || 'Front Desk'}</span>
                 <span><strong>Triage:</strong> {patientToken.triage_station || 'Station 1'}</span>
              </div>
            </div>
          </div>

          {/* Footer Info */}
          <div className="card-footer-meta" style={{ marginBottom: '0' }}>
            <div className="meta-info-item">
              <Clock size={14} />
              <span>{currentTime}</span>
            </div>
            <div className="meta-info-item">
              <Activity size={14} />
              <span>Priority: {patientToken.priority_name || 'Standard'}</span>
            </div>
          </div>

          <div className="card-bg-glow"></div>
        </motion.div>
      </div>

      <div style={{ display: 'flex', gap: '1rem', width: '100%', maxWidth: '400px' }}>
        <button 
          className="btn btn-primary" 
          style={{ flex: 1, padding: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem', borderRadius: '1rem', fontWeight: 600 }}
          onClick={handleDownload}
          disabled={isDownloading}
        >
          <Download size={20} />
          {isDownloading ? 'Processing...' : 'Save as PNG'}
        </button>
        <button 
          className="btn btn-ghost" 
          style={{ width: '60px', borderRadius: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.05)' }}
          onClick={handleShare}
        >
          <Share2 size={20} />
        </button>
      </div>
    </div>
  );
};

export default MyTokenCard;
